USE [master]
GO

/****** Object:  Database [FasTechDB]    Script Date: 3/23/2021 4:38:09 PM ******/
CREATE DATABASE [FasTechDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FasTechDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FasTechDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FasTechDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FasTechDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FasTechDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FasTechDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FasTechDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FasTechDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FasTechDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FasTechDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FasTechDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FasTechDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FasTechDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FasTechDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FasTechDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FasTechDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FasTechDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FasTechDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FasTechDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FasTechDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FasTechDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FasTechDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FasTechDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FasTechDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FasTechDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FasTechDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FasTechDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FasTechDB] SET RECOVERY FULL 
GO

ALTER DATABASE [FasTechDB] SET  MULTI_USER 
GO

ALTER DATABASE [FasTechDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FasTechDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FasTechDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FasTechDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FasTechDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FasTechDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FasTechDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FasTechDB] SET  READ_WRITE 
GO

